name: recursive_clustering
channels:
  - conda-forge
dependencies:
  - matplotlib
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - ipykernel
  - ipywidgets
  - seaborn
  - pip
  - pip:
      - openml
      - -e .
